name: TRS

channels:
  - defaults
  - conda-forge
  - bioconda
  - pypi

dependencies:
  - python=3.6.13
  - biopython=1.78
  - pandas=1.1.5
  - numpy=1.19.2
  - matplotlib=3.3.4
  - scikit-learn
  - seaborn
  - jupyterlab
  - nb_conda_kernels
  - ipywidgets
  - ipyparallel
  - prometheus_client
  - parasail-python=1.2

