#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include <stdio.h>
#include <stdlib.h>
/*
+---------------------------------------------------------------------------+
| NPt – data structure serving to store the position of s single nucleotide |
| in the genome and the sign representing this nucleotide.                  |
+---------------------------------------------------------------------------+
*/
typedef struct _NPt {

    long long no;
    char sgn;

    struct _NPt *next;
    struct _NPt *prev;

} NPt;
/*
+---------------------------------------------------------------------------+
| NLt – data structure serving to store the data on the genome with the     |
| use of data structure NPt. in the genome and the sign representing this   |
| nucleotide.                                                               |
+---------------------------------------------------------------------------+
*/
typedef struct _NLt {

    NPt *head;
    NPt *tail;

} NLt;
/*
+---------------------------------------------------------------------------+
| MPt – data structure serving to store the number of the TRS motifs, the   |
| number of the class of TRS motifs and a single sign representing the      |
| nucleotide of the TRS motif from the file trs.txt.                        |
+---------------------------------------------------------------------------+
*/
typedef struct _MPt {

    int no;
    int cl;
    char n;

    struct _MPt *r;
    struct _MPt *b;

} MPt;
/*
+---------------------------------------------------------------------------+
| MLt – data structure serving to store the TRS motifs contained in the file|
| trs.txt with the use of data structure MPt.                               |
+---------------------------------------------------------------------------+
*/
typedef struct _MLt {

    MPt *rt;
    MPt *r;
    MPt *b;

} MLt;
/*
+---------------------------------------------------------------------------+
| VPt – data structure serving to store the left and the right positions    |
| of the flanking sequence which are found, as well as TRS constituting the |
| base for the flanking sequence.                                           |
+---------------------------------------------------------------------------+
*/
typedef struct _VPt {

    int inf;

    int no;
    int cl;

    long long int ps;
    long long int pe;

    NLt *nlt;

    struct _VPt *next;
    struct _VPt *prev;

} VPt;
/*
+---------------------------------------------------------------------------+
| VLt – data structure serving to store the position of the flanking        |
| sequence.                                                                 |
+---------------------------------------------------------------------------+
*/
typedef struct _VLt {

    VPt *head;
    VPt *tail;

} VLt;
/*
+---------------------------------------------------------------------------+
| InitNLt() – this function initializes the linked list of NLt type.        |
+---------------------------------------------------------------------------+
*/
void InitNLt(NLt *nlt) {

    nlt->head = NULL;
    nlt->tail = NULL;
}
/*
+---------------------------------------------------------------------------+
| InitMLt() – this function initializes the linked list of MLt type.        |
+---------------------------------------------------------------------------+
*/
void InitMLt(MLt *l) {

    l->rt = NULL;
    l->r =  NULL;
    l->b =  NULL;
}
/*
+---------------------------------------------------------------------------+
| InitVLt() – this function initializes the linked list of VLt type.        |
+---------------------------------------------------------------------------+
*/
void InitVLt(VLt *vlt) {

    vlt->head = NULL;
    vlt->tail = NULL;
}
/*
+---------------------------------------------------------------------------+
| FreeNLt() – this function frees memory assigned to the linked list of NLt |
| type.                                                                     |
+---------------------------------------------------------------------------+
*/
void FreeNLt(NLt *nlt) {

    if (nlt->head != NULL) {

        NPt *ctnpt = nlt->head, *tmp;

        while (ctnpt != NULL) {
            tmp = ctnpt->next;
            free(ctnpt);
            ctnpt = tmp;
        }
    }
}
/*
+---------------------------------------------------------------------------+
| void FreeMLt() – this function frees the memory assigned to the linked    |
| list of MLt type.                                                         |
+---------------------------------------------------------------------------+
*/
void FreeMLt(MLt *mlt) {

    if (mlt->rt != NULL) {

        MPt *ctmpt1 = mlt->rt, *ctmpt2, *tmp;

        while (ctmpt1 != NULL) {

            ctmpt2 = ctmpt1;

            while (ctmpt2 != NULL) {
                tmp = ctmpt2->r;
                free(ctmpt2);
                ctmpt2 = tmp;
            }

            ctmpt1 = ctmpt1->b;
        }
    }
}
/*
+---------------------------------------------------------------------------+
| void FreeVLt() – this function frees the memory assigned to the linked    |
| list of VLt type.                                                         |
+---------------------------------------------------------------------------+
*/
void FreeVLt(VLt *vlt) {

    if (vlt->head != NULL) {

        VPt *ctvpt = vlt->head, *tmp;

        while (ctvpt != NULL) {
            tmp = ctvpt->next;
            FreeNLt(ctvpt->nlt);
            free(ctvpt);
            ctvpt = tmp;
        }
    }
}
/*
+---------------------------------------------------------------------------+
| AddPtToNLt() – this function adds data of NPt type to the linked list of  |
| NLt type.                                                                 |
+---------------------------------------------------------------------------+
*/
int AddPtToNLt(NLt *nlt, long long int no, char sgn) {

    NPt *npt = (NPt*)malloc(sizeof(NPt));

    int ret = 1;

    if (npt == NULL) ret = -1;
    else {
        npt->no = no;
        npt->sgn = sgn;

        npt->next = NULL;
        npt->prev = NULL;

        if (nlt->head == NULL) {
            nlt->head = npt;
            nlt->tail = npt;
        }
        else {
            nlt->tail->next = npt;
            npt->prev = nlt->tail;
            nlt->tail = nlt->tail->next;
        }
    }
    return ret;
}
/*
+---------------------------------------------------------------------------+
| AddPtToMLt() – this function adds data of MPt type to the linked list of  |
| MLt type.                                                                 |
+---------------------------------------------------------------------------+
*/
int AddPtToMLt(int k, MLt *mlt, int no, int cl, char sgn) {

    MPt *mpt = (MPt*)malloc(sizeof(MPt));

    int ret = 1;

    if (mpt == NULL) ret = -1;
    else {
        mpt->no = no;
        mpt->cl = cl;
        mpt->n  = sgn;
        mpt->r  = NULL;
        mpt->b  = NULL;

        if (mlt->rt == NULL) {
            mlt->rt = mpt;
            mlt->r = mpt;
            mlt->b = mpt;
        }
        else {
            if (k == 1) {
                mlt->r->r = mpt;
                mlt->r = mpt;
            }
            else
                if (k == 2) {
                    mlt->b->b = mpt;
                    mlt->b = mpt;
                    mlt->r = mpt;
                }
        }
    }

    return ret;
}
/*
+---------------------------------------------------------------------------+
| AddPtToVLt() – this function adds data of VPt type to the linked list of  |
| VLt type.                                                                 |
+---------------------------------------------------------------------------+
*/
int AddPtToVLt(VLt *vlt, int inf, int no, int cl, long long int ps, long long int pe, NLt *nlt) {

    VPt *vpt = (VPt*)malloc(sizeof(VPt));

    int ret = 1;

    if (vpt == NULL) ret = -1;
    else {
        vpt->inf = inf;

        vpt->no = no;
        vpt->cl = cl;
        vpt->ps = ps;
        vpt->pe = pe;

        vpt->nlt = nlt;

        vpt->next = NULL;
        vpt->prev = NULL;

        if (vlt->head == NULL) {
            vlt->head = vpt;
            vlt->tail = vpt;
        }
        else {
            vlt->tail->next = vpt;
            vpt->prev = vlt->tail;
            vlt->tail = vlt->tail->next;
        }
    }

    return ret;
}
/*
+---------------------------------------------------------------------------+
| PrtNLtToFile() – this function records the content of the linked list in  |
| a file.                                                                   |
+---------------------------------------------------------------------------+
*/
int PrtNLtToFile(FILE *f, NPt *npt, char *file_content) {

    NPt *ctnpt = npt;

    int ret = 1;
    char single_char;
    while (ctnpt != NULL) {
        single_char = ctnpt->sgn;
        strcat(file_content, &single_char);
        if (fprintf(f,"%c",single_char) < 0) {
            ret = -1;
            break;
        }

        ctnpt = ctnpt->next;
    }

    return ret;
}
/*
+---------------------------------------------------------------------------+
| PrtNLtToFile() – this function records the content of the linked list in  |
| a buffer. (RAB)                                                                   |
+---------------------------------------------------------------------------+
*/
int PrtNLtToBuffer(char *buffer, NPt *npt) {

    NPt *ctnpt = npt;

    int ret = 1;
    int l = 0;
    char *line = (char*)calloc(256, sizeof(char));

    while (ctnpt != NULL) {
        l = sprintf(line, "%c",ctnpt->sgn);
        l = strcat(buffer, line);
        printf("sgn %s", line);
        if (l < 0) {
            ret = -1;
            break;
        }
        ctnpt = ctnpt->next;
    }

    return ret;
}
/*
+---------------------------------------------------------------------------+
| ImportGenome() – this function imports the genome from the file           |
| sequence.fasta and records it in the linked list of NLt type.             |
+---------------------------------------------------------------------------+
*/
long long int ImportGenome(char *fn, NLt *nlt) {

    long long int ret = 0;

    char sgn;

    FILE *f;

    if ((f = fopen(fn,"r")) != NULL) {

        while ((sgn = fgetc(f)) != EOF) {

            if (sgn == '>') {

                while ((sgn = fgetc(f)) != EOF) if (sgn == '\n') break;

                if (ferror(f) != 0)  {
                    fclose(f);
                    ret = -110;
                }
            }
            else {

                if (sgn != '\n' && sgn != '\t' && sgn != '\v' && sgn != ' '  && sgn != '\0' && sgn != '\b' && sgn != '\r' && sgn != EOF  && sgn != 'a'  && sgn !='\f')
                {
                    ret++;

                    if (AddPtToNLt(nlt,ret,sgn) < 0) {
                        fclose(f);
                        ret = -120;
                    }
                }
            }
        }

        if (ferror(f) == 0) fclose(f);
        else {
            fclose(f);
            ret = -110;
        }
    }
    else ret = -100;

    if ((ret != -100) && (nlt->head == NULL)) ret = -130;

    return ret;
}
/*
+---------------------------------------------------------------------------+
| CopyNLt() – this function creates a copy of the linked list of NLt type.  |
+---------------------------------------------------------------------------+
*/
int CopyNLt(NLt *rnlt, NLt *nlt) {

    NPt *ctnpt = nlt->head;

    int ret = 1;

    if (ctnpt != NULL) {

        while (ctnpt != NULL) {

            if (AddPtToNLt(rnlt,ctnpt->no,ctnpt->sgn) < 0) {
                ret = -150;
                break;
            }

            ctnpt = ctnpt->next;
        }
    }
    else ret = -140;

    return ret;
}
/*
+---------------------------------------------------------------------------+
| JoinNLtWithNLt() – this function combines two linked lists of NLt type in |
| such a way that the end of one linked list is added another linked list.  |
+---------------------------------------------------------------------------+
*/
void JoinNLtWithNLt(NLt *nlt1, NLt *nlt2) {

    if (nlt2->head != NULL) {

        if (nlt1->head == NULL) {
            nlt1->head = nlt2->head;
            nlt1->tail = nlt2->tail;
        }
        else {
            nlt1->tail->next = nlt2->head;
            nlt2->head->prev = nlt1->tail;
            nlt1->tail = nlt2->tail;
        }
    }
}
/*
+---------------------------------------------------------------------------+
| ImportTRSToMLt() – this function imports TRS motifs from the file         |
| trs.txt and records them in the linked list of MLt type.                  |
+---------------------------------------------------------------------------+
*/
int ImportTRSToMLt(char *fn, MLt *mlt) {

    int p = 0, pl = 0, no = 0, cl = 1, reset = 0;

    char sgn, l;

    FILE *f;

    if ((f = fopen(fn,"r")) != NULL) {

        if ((l = fgetc(f)) != EOF) {

            if (l != '#') pl = -170;
        }
        else pl = -170;

        if (pl >= 0) {

            while ((sgn = fgetc(f)) != EOF) {

                if (sgn == 'A' ||  sgn == 'C' || sgn == 'G' || sgn == 'T' || sgn == '#' || sgn == '\n') {

                    if (reset == 1) {
                        reset = 0;
                        p = 0;
                    }

                    if ((sgn == 'A' || sgn == 'C' || sgn == 'G' || sgn == 'T') && (l == '#')) {

                        p++;

                        no++;

                        if (AddPtToMLt(2,mlt,no,cl,sgn) < 0) {
                            pl = -180;
                            break;
                        }
                    }

                    if ((sgn == 'A' || sgn == 'C' || sgn == 'G' || sgn == 'T') && (l == 'A' || l == 'C' || l == 'G' || l == 'T')) {

                        p++;

                        if (AddPtToMLt(1,mlt,no,cl,sgn) < 0) {
                            pl = -180;
                            break;
                        }
                    }

                    if ((sgn == '#') && (l == 'A' || l == 'C' || l == 'G' || l == 'T')) {

                        if ((p % 3) != 0) {
                            pl = -190;
                            break;
                        }
                        else {

                            if (pl == 0) {
                                reset = 1;
                                pl = p;
                            }
                            else {

                                if (pl == p) reset = 1;
                                else {
                                    pl = -190;
                                    break;
                                }
                            }
                        }
                    }

                    if ((sgn == '\n') && (l == 'A' || l == 'C' || l == 'G' || l == 'T')) {

                        cl++;

                        if ((p % 3) != 0) {
                            pl = -190;
                            break;
                        }
                        else {

                            if (pl == 0) {
                                reset = 1;
                                pl = p;
                            }
                            else {

                                if (pl == p) reset = 1;
                                else {
                                    pl = -190;
                                    break;
                                }
                            }
                        }
                    }

                    if ((sgn == '\n' && l == '\n') || (sgn == '#' && l == '#') || (sgn == '\n' && l == '#')) {
                        pl = -170;
                        break;
                    }

                    l = sgn;
                }
                else {
                    pl = -170;
                    break;
                }
            }
        }

        if (pl >= 0) {

            if (ferror(f) == 0) {

                if ((p % 3) != 0) {
                    pl = -190;
                    fclose(f);
                }
                else
                {
                    if (pl == p) fclose(f);
                    else {
                        pl = -190;
                        fclose(f);
                    }
                }
            }
            else {
                pl = -200;
                fclose(f);
            }
        }
    }
    else pl = -160;

    return pl;
}
/*
+---------------------------------------------------------------------------+
|  FirstToLastInListNLt() – this function shifts the first element of the   |
|  linked list NLt to the end of the linked list and varies the position and|
|  sign representing the nucleotide.                                        |
+---------------------------------------------------------------------------+
*/
void FirstToLastInListNLt(NLt *nlt, long long int no, char sgn) {

    NPt *first = nlt->head->next;

    nlt->head->next->prev = NULL;
    nlt->head->no = no;
    nlt->head->sgn = sgn;
    nlt->head->next = NULL;
    nlt->head->prev = nlt->tail;
    nlt->tail->next = nlt->head;
    nlt->tail = nlt->head;
    nlt->head = first;
}
/*
+---------------------------------------------------------------------------+
| UpLe() – this function replace a small letter representing nucleotide     |
| into a capital letter representing nucleotide.                            |
+---------------------------------------------------------------------------+
*/
char UpLe(char sgn)
{
    if(sgn>=97) sgn = sgn-32;

    return sgn;
 }
/*
+---------------------------------------------------------------------------+
|  CompareOneTRS() – this function checks if there occurs one TRS motif.    |
+---------------------------------------------------------------------------+
*/
int CompareOneTRS(MPt *mpt, NPt *npt) {

    MPt *ctmpt = mpt;
    NPt *ctnpt = npt;

    int ret = 1;

    do {

        if (UpLe(ctmpt->n) != UpLe(ctnpt->sgn)) {
            ret = 0;
            break;
        }
        else {
            ctmpt = ctmpt->r;
            ctnpt = ctnpt->next;
        }

    } while (ctnpt != NULL);

    return ret;
}
/*
+---------------------------------------------------------------------------+
| FindFistrTRSPosition() – this function searches the left TRS flanking     |
| sequence.                                                                 |
+---------------------------------------------------------------------------+
*/
VPt* FindFistrTRSPosition(MLt *mlt, NLt *nlt) {

    NPt *npt3 = nlt->head, *npt1 = nlt->head;

    MPt *ctmpt = mlt->rt;
    NPt *ctnpt = nlt->head;

    int ret = 0;

    VPt *vpt = (VPt*)malloc(sizeof(VPt)), *rvpt = NULL;

    if (vpt != NULL) {

        vpt->inf = 0;

        vpt->no = 0;
        vpt->cl = 0;
        vpt->ps = 0;
        vpt->pe = 0;

        vpt->nlt = NULL;

        vpt->next = NULL;
        vpt->prev = NULL;

        while (ctmpt != NULL) {

            if (CompareOneTRS(ctmpt, ctnpt) == 1) {

                NLt  *nlt1 = (NLt*)malloc(sizeof(NLt));

                if (nlt1 != NULL) {

                    InitNLt(nlt1);

                    for(int i = 1; i <= 3; i++) {

                        if (AddPtToNLt(nlt1,npt1->no,npt1->sgn) < 0) {
                            ret = -1;
                            break;
                        }

                        npt1 = npt1->next;
                    }

                    if (ret == 0) {

                        vpt->inf = 1;

                        vpt->no = ctmpt->no;
                        vpt->cl = ctmpt->cl;
                        vpt->ps = ctnpt->no;
                        vpt->pe = -1;

                        vpt->nlt = nlt1;
                    }
                    else {
                        FreeNLt(nlt1);
                        break;
                    }
                }
                else {
                    ret = -1;
                    break;
                }

                break;
            }

            ctmpt = ctmpt->b;
        }

    }
    else ret = -1;

    if (ret == -1) {
        rvpt = vpt;
        vpt = NULL;
        free(rvpt);
    }

    return vpt;

}
/*
+---------------------------------------------------------------------------+
|  CompareLists() – this function checks if the TRS repeats itself.         |
+---------------------------------------------------------------------------+
*/
int CompareLists(NPt *npt1, NPt *npt2) {

    NPt *ctnpt1 = npt1;
    NPt *ctnpt2 = npt2;

    int ret = 1;

    do {

        if (ctnpt2 == NULL) {
            ret = -1;
            break;
        }

        if (UpLe(ctnpt1->sgn) != UpLe(ctnpt2->sgn)) {
            ret = 0;
            break;
        }
        else {
            ctnpt1 = ctnpt1->next;
            ctnpt2 = ctnpt2->next;
        }

    } while (ctnpt1 != NULL);

    return ret;
}
/*
+---------------------------------------------------------------------------+
|  LC_TRSPositionsFindAndSaveToVLt() – this function finds the positions   |
|  of flanking sequences and records them in the linked list VLt together   |
|  with their TRSs which make the base of these flanking sequences for the  |
|  linear case.                                                             |
+---------------------------------------------------------------------------+
*/
int LC_TRSPositionsFindAndSaveToVLt(MLt *mlt, NLt *nlt, VLt *vlt, int len) {

    int i, r, ret = 1, con = 0;

    NPt *ctnpt = nlt->head;

    VPt *vpt;

    NLt *snlt = (NLt*)malloc(sizeof(NLt));

    if (snlt != NULL) {

        InitNLt(snlt);

        for(i = 1; i <= len; i++) {

            if (ctnpt != NULL) {

                if ((AddPtToNLt(snlt,ctnpt->no,ctnpt->sgn)) < 0) {
                    ctnpt = NULL;
                    ret = -220;
                    break;
                }
            }
            else {
                ret = -230;
                break;
            }

            if (i != len) ctnpt = ctnpt->next;
        }

        if ((i - 1) == len) con = 3;
    }
    else {
        ctnpt = NULL;
        ret = -210;
    }

    while (ctnpt != NULL) {

        if (con == 1) {

            for(i = 1; i <= len; i++) {

                if (ctnpt != NULL) FirstToLastInListNLt(snlt,ctnpt->no,ctnpt->sgn);
                else {
                    con = 9;
                    break;
                }

                if (i != len) ctnpt = ctnpt->next;
            }

            if ((i - 1) == len) con = 3;
        }

        if (con == 2) {

            FirstToLastInListNLt(snlt,ctnpt->no,ctnpt->sgn);

            con = 3;
        }

        if (con == 3) {

            if ((vpt = FindFistrTRSPosition(mlt,snlt)) == NULL) {
                ret = -240;
                break;
            }
            else {

                if (vpt->inf == 0) {

                    VPt *rvpt = vpt;
                    vpt = NULL;
                    free(rvpt);

                    ctnpt = ctnpt->next;
                    con = 2;
                }
                else con = 4;
            }
        }

        if (con == 4) {

            if ((r = CompareLists(vpt->nlt->head,ctnpt->next)) == 0) {

                if (AddPtToVLt(vlt,vpt->inf,vpt->no,vpt->cl,vpt->ps,ctnpt->no,vpt->nlt) < 0) {
                    ret = -240;
                    break;
                }
                else {
                    VPt *rvpt = vpt;
                    vpt = NULL;
                    free(rvpt);
                }

                ctnpt = ctnpt->next;

                con = 1;
            }
            else {

                if (r == 1) {

                    if ((ctnpt->next != NULL) && (ctnpt->next->next != NULL) && (ctnpt->next->next->next != NULL)) ctnpt = ctnpt->next->next->next;

                    con = 4;
                }
                else {

                    if (AddPtToVLt(vlt,vpt->inf,vpt->no,vpt->cl,vpt->ps,ctnpt->no,vpt->nlt) < 0) {
                        ret = -240;
                        break;
                    }
                    else {
                        VPt *rvpt = vpt;
                        vpt = NULL;
                        free(rvpt);
                    }

                    con = 9;
                }
            }
        }

        if (con == 9) {
            ret = 1;
            break;
        }
    }

    return ret;
}
/*
+---------------------------------------------------------------------------+
|  CC_TRSPositionsFindAndSaveToVLt() – this function finds the positions of|
|  flanking sequences and records them in the linked list VLt together with |
|  their TRSs which make the base for these flanking sequences for the      |
|  linear circular case.                                                    |
+---------------------------------------------------------------------------+
*/
int CC_TRSPositionsFindAndSaveToVLt(MLt *mlt, NLt *nlt, VLt *vlt, int len) {

    int i, r, k = 0, ret = 1, con = 0, stop = 0;

    NPt *ctnpt = nlt->head;
    VPt *vpt;

    NLt *snlt = (NLt*)malloc(sizeof(NLt));

    if (snlt != NULL) {

        InitNLt(snlt);

        for(i = 1; i <= len; i++) {

            if (ctnpt != NULL) {

                if (AddPtToNLt(snlt,ctnpt->no,ctnpt->sgn) < 0) {
                    ctnpt = NULL;
                    ret = -260;
                    break;
                }

                if (k < ctnpt->no) k = ctnpt->no;
                else stop = 1;
            }
            else {
                ret = -270;
                break;
            }

            if (i != len) ctnpt = ctnpt->next;
        }

        if ((i - 1) == len) con = 3;
    }
    else {
        ctnpt = NULL;
        ret = -250;
    }

    while (ctnpt != NULL) {

        if (stop == 2) con = 9;

        if (con == 1) {

            for(i = 1; i <= len; i++) {

                if (ctnpt != NULL) {

                    FirstToLastInListNLt(snlt,ctnpt->no,ctnpt->sgn);

                    if (k < ctnpt->no) k = ctnpt->no;
                    else stop = 1;
                }
                else {
                    con = 9;
                    break;
                }

                if (i != len) ctnpt = ctnpt->next;
            }

            if ((i - 1) == len) con = 3;
        }

        if (con == 2) {

            FirstToLastInListNLt(snlt,ctnpt->no,ctnpt->sgn);

            if (k < ctnpt->no) k = ctnpt->no;
            else stop = 1;

            con = 3;
        }

        if (con == 3) {

            if ((vpt = FindFistrTRSPosition(mlt,snlt)) == NULL) {
                ret = -280;
                break;
            }
            else {

                if (vpt->inf == 0) {

                    VPt *rvpt = vpt;
                    vpt = NULL;
                    free(rvpt);

                    ctnpt = ctnpt->next;
                    con = 2;
                }
                else con = 4;
            }
        }

        if (con == 4)
        {
            if ((r = CompareLists(vpt->nlt->head,ctnpt->next)) == 0) {

                if (AddPtToVLt(vlt,vpt->inf,vpt->no,vpt->cl,vpt->ps,ctnpt->no,vpt->nlt) < 0) {
                    ret = -280;
                    break;
                }

                if (stop != 1) con = 1;
                else {
                    if (vpt->ps < ctnpt->no) {
                        con = 1;
                        stop = 2;
                    }
                    else con = 1;
                }

                VPt *rvpt = vpt;
                vpt = NULL;
                free(rvpt);

                ctnpt = ctnpt->next;
            }
            else {

                if (r == 1) {

                    if ((ctnpt->next != NULL) && (ctnpt->next->next != NULL) && (ctnpt->next->next->next != NULL)) {

                        ctnpt = ctnpt->next->next->next;

                        if (k < ctnpt->no) k = ctnpt->no;
                        else stop = 1;
                    }

                    con = 4;
                }
                else {

                    if (AddPtToVLt(vlt,vpt->inf,vpt->no,vpt->cl,vpt->ps,ctnpt->no,vpt->nlt) < 0) {
                        ret = -280;
                        break;
                    }
                    else {
                        VPt *rvpt = vpt;
                        vpt = NULL;
                        free(rvpt);
                    }

                    con = 9;
                }
            }
        }

        if (con == 9) {
            ret = 1;
            break;
        }
    }

    return ret;
}
/*
+---------------------------------------------------------------------------+
|  LC_InteriorsFindAndSaveToFile() – this function generates the file       |
|  interiors.txt for the linear case with conditions.                       |
+---------------------------------------------------------------------------+
*/
int LC_InteriorsFindAndSaveToFile(char *ifn, VLt *vlt, NLt *nlt, long long int min, long long int max, char *file_content) {

    NPt *ctnpt = nlt->head;
    VPt *ctvpt = vlt->head;

    int ret = 1;
    int l;

    FILE *f;
    //const int out_buffer_size=20000;
    //char *file_content = (char*)calloc(out_buffer_size, sizeof(char));
    char *line = (char*)calloc(256, sizeof(char));


    if ((f = fopen(ifn,"w")) != NULL) {
        char header[] = "L-NoClass;L-No;LFS;Len(LFS);L-POS(LFS);R-POS(LFS);R-NoClass;R-No;RFS;Len(RFS);L-POS(RFS);R-POS(RFS);>SEQ;Len(SEQ)\n";
        strcat(file_content, header);
        if (fprintf(f, header) < 0) {
            ret = -300;
            ctvpt->next = NULL;
        }

        while (ctvpt->next != NULL) {

            if (((ctvpt->next->ps - ctvpt->pe) > min) && ((ctvpt->next->ps - ctvpt->pe) < (max +2))) {

                if ((ctvpt->cl > 0)&&(ctvpt->cl < 10)) {
                    
                    if ((ctvpt->no > 0)&&(ctvpt->no < 10)) {
                        l = sprintf(line, "0%d;0%d;",ctvpt->cl,ctvpt->no);
                        strcat(file_content, line);
                        if (fprintf(f,"0%d;0%d;",ctvpt->cl,ctvpt->no) < 0) {
                            ret = -300;
                            break;
                        }
                    }
                    else {
                        l = sprintf(line, "0%d;%d;",ctvpt->cl,ctvpt->no);
                        strcat(file_content, line);
                        if (fprintf(f,"0%d;%d;",ctvpt->cl,ctvpt->no) < 0) {
                            ret = -300;
                            break;
                        }
                    }
                }
                else {

                    if ((ctvpt->no > 0)&&(ctvpt->no < 10)) {
                        l = sprintf(line, "%d;0%d;",ctvpt->cl,ctvpt->no);
                        strcat(file_content, line);
                        if (fprintf(f,"%d;0%d;",ctvpt->cl,ctvpt->no) < 0) {
                            ret = -300;
                            break;
                        }
                    }
                    else {
                        l = sprintf(line, "%d;%d;",ctvpt->cl,ctvpt->no);
                        strcat(file_content, line);
                        if (fprintf(f,"%d;%d;",ctvpt->cl,ctvpt->no) < 0) {
                            ret = -300;
                            break;
                        }
                    }
                }

                for(int i = 1; i <= (abs(ctvpt->pe - ctvpt->ps + 1)/3); i++) {
                    //PrtNLtToBuffer(file_content, ctvpt->nlt->head);
                    if (PrtNLtToFile(f,ctvpt->nlt->head,file_content) < 0) {
                        ret = -300;
                        break;
                    }
                }

                if (ret == -300) break;

                if ((ctvpt->next->cl > 0)&&(ctvpt->next->cl < 10))
                {
                    if ((ctvpt->next->no > 0)&&(ctvpt->next->no < 10)) {
                        l = sprintf(line, ";%d;%d;%d;0%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                        strcat(file_content, line);
                        if (fprintf(f,";%d;%d;%d;0%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                            ret = -300;
                            break;
                        }
                    }
                    else {
                        l = sprintf(line, ";%d;%d;%d;0%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                        strcat(file_content, line);
                        if (fprintf(f,";%d;%d;%d;0%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                            ret = -300;
                            break;
                        }
                    }
                }
                else {

                    if ((ctvpt->next->no > 0)&&(ctvpt->next->no < 10)) {
                        l = sprintf(line, ";%d;%d;%d;%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps, ctvpt->pe, ctvpt->next->cl,ctvpt->next->no);
                        strcat(file_content, line);
                        if (fprintf(f,";%d;%d;%d;%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps, ctvpt->pe, ctvpt->next->cl,ctvpt->next->no) < 0) {
                            ret = -300;
                            break;
                        }
                    }
                    else {
                        l = sprintf(line, ";%d;%d;%d;%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                        strcat(file_content, line);
                        if (fprintf(f,";%d;%d;%d;%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                            ret = -300;
                            break;
                        }
                    }
                }

                for(int i = 1; i <= (abs(ctvpt->next->pe - ctvpt->next->ps + 1)/3); i++) {
                    //PrtNLtToBuffer(file_content, ctvpt->next->nlt->head);
                    if (PrtNLtToFile(f,ctvpt->next->nlt->head, file_content) < 0) {
                        ret = -300;
                        break;
                    }
                }

                if (ret == -300) break;

                l = sprintf(line, ";%d;%d;%d;>",abs(ctvpt->next->pe - ctvpt->next->ps + 1),ctvpt->next->ps,ctvpt->next->pe);
                strcat(file_content, line);
                if (fprintf(f,";%d;%d;%d;>",abs(ctvpt->next->pe - ctvpt->next->ps + 1),ctvpt->next->ps,ctvpt->next->pe) < 0) {
                    ret = -300;
                    break;
                }

                while (ctvpt->pe != ctnpt->no) {
                    ctnpt = ctnpt->next;
                }

                ctnpt = ctnpt->next;

                int li = 0;

                while (ctnpt->no != ctvpt->next->ps) {

                    l = sprintf(line, "%c",ctnpt->sgn);
                    strcat(file_content, line);
                    if (fprintf(f,"%c",ctnpt->sgn) < 0) {
                        ret = -300;
                        break;
                    }

                    li++;

                    ctnpt = ctnpt->next;
                }

                if (ret == -300) break;

                l = sprintf(line, ";%d\n",li);
                strcat(file_content, line);
                if (fprintf(f,";%d\n",li) < 0) {
                    ret = -300;
                    break;
                }
            }

            ctvpt = ctvpt->next;
        }

        fclose(f);
    }
    else ret = -290;
    return ret;
}
/*
+---------------------------------------------------------------------------+
|  CC_InteriorsFindAndSaveToFile() – this function generates the file       |
|  interiors.txt for the circular case with conditions.                     |
+---------------------------------------------------------------------------+
*/
int CC_InteriorsFindAndSaveToFile(char *ifn, VLt *vlt, NLt *nlt, long long int size, long long int min, long long int max, char *file_content) {

    NPt *ctnpt = nlt->head;
    VPt *ctvpt = vlt->head;

    int ret = 1;
    int l = 0;

    FILE *f;
    char *line = (char*)calloc(256, sizeof(char));

    if ((f = fopen(ifn,"w")) != NULL) {
        char header[] = "L-NoClass;L-No;LFS;Len(LFS);L-POS(LFS);R-POS(LFS);R-NoClass;R-No;RFS;Len(RFS);L-POS(RFS);R-POS(RFS);>SEQ;Len(SEQ)\n";
        strcat(file_content, header); 
        if (fprintf(f,"L-NoClass;L-No;LFS;Len(LFS);L-POS(LFS);R-POS(LFS);R-NoClass;R-No;RFS;Len(RFS);L-POS(RFS);R-POS(RFS);>SEQ;Len(SEQ)\n") < 0) {
            ret = -320;
            ctvpt->next = NULL;
        }

        while (ctvpt->next != NULL) {

            if (ctvpt->next->ps > ctvpt->pe) {

                if (((ctvpt->next->ps - ctvpt->pe) > min) && ((ctvpt->next->ps - ctvpt->pe) < (max +2))) {

                    if ((ctvpt->cl > 0)&&(ctvpt->cl < 10)) {

                        if ((ctvpt->no > 0)&&(ctvpt->no < 10)) {
                            l = sprintf(line, "0%d;0%d;",ctvpt->cl,ctvpt->no);
                            strcat(file_content, line);
                            if (fprintf(f,"0%d;0%d;",ctvpt->cl,ctvpt->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                        else {
                            l = sprintf(line, "0%d;%d;",ctvpt->cl,ctvpt->no);
                            strcat(file_content, line);
                            if (fprintf(f,"0%d;%d;",ctvpt->cl,ctvpt->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                    }
                    else {

                        if ((ctvpt->no > 0)&&(ctvpt->no < 10)) {
                            l = sprintf(line, "%d;0%d;",ctvpt->cl,ctvpt->no);
                            strcat(file_content, line);
                            if (fprintf(f,"%d;0%d;",ctvpt->cl,ctvpt->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                        else {
                            l = sprintf(line, "%d;%d;",ctvpt->cl,ctvpt->no);
                            strcat(file_content, line);
                            if (fprintf(f,"%d;%d;",ctvpt->cl,ctvpt->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                    }

                    for(int i = 1; i <= (abs(ctvpt->pe - ctvpt->ps + 1)/3); i++) {
                        //PrtNLtToBuffer(file_content, ctvpt->next->nlt->head);
                        if (PrtNLtToFile(f,ctvpt->nlt->head, file_content) < 0) {
                            ret = -320;
                            break;
                        }
                    }

                    if (ret == -320) break;

                    if ((ctvpt->next->cl > 0)&&(ctvpt->next->cl < 10)) {

                        if ((ctvpt->next->no > 0)&&(ctvpt->next->no < 10)) {
                            l = sprintf(line, ";%d;%d;%d;0%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                            strcat(file_content, line);
                            if (fprintf(f,";%d;%d;%d;0%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                        else {
                            l = sprintf(line, ";%d;%d;%d;0%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                            strcat(file_content, line);
                            if (fprintf(f,";%d;%d;%d;0%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                    }
                    else {

                            if ((ctvpt->next->no > 0)&&(ctvpt->next->no < 10)) {
                            l = sprintf(line, ";%d;%d;%d;%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                            strcat(file_content, line);
                            if (fprintf(f,";%d;%d;%d;%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                        else {
                            l = sprintf(line, ";%d;%d;%d;%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                            strcat(file_content, line);
                            if (fprintf(f,";%d;%d;%d;%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                    }

                    for(int i = 1; i <= (abs(ctvpt->next->pe - ctvpt->next->ps + 1)/3); i++) {
                        //PrtNLtToBuffer(file_content, ctvpt->next->nlt->head);
                        if (PrtNLtToFile(f,ctvpt->next->nlt->head, file_content) < 0) {
                            ret = -320;
                            break;
                        }
                    }

                    if (ret == -320) break;
                    l = sprintf(line, ";%d;%d;%d;>",abs(ctvpt->next->pe - ctvpt->next->ps + 1),ctvpt->next->ps,ctvpt->next->pe);
                    strcat(file_content, line);
                    if (fprintf(f,";%d;%d;%d;>",abs(ctvpt->next->pe - ctvpt->next->ps + 1),ctvpt->next->ps,ctvpt->next->pe) < 0) {
                        ret = -320;
                        break;
                    }

                    while (ctvpt->pe != ctnpt->no){
                        ctnpt = ctnpt->next;
                    }

                    ctnpt = ctnpt->next;

                    int li = 0;

                    while (ctnpt->no != ctvpt->next->ps) {
                        l = sprintf(line, "%c",ctnpt->sgn);
                        strcat(file_content, line);
                        if (fprintf(f,"%c",ctnpt->sgn) < 0) {
                            ret = -320;
                            break;
                        }

                        li++;

                        ctnpt = ctnpt->next;
                    }

                    if (ret == -320) break;
                    l = sprintf(line, ";%d\n",li);
                    strcat(file_content, line);
                    if (fprintf(f,";%d\n",li) < 0) {
                        ret = -320;
                        break;
                    }
                }

                ctvpt = ctvpt->next;
            }
            else {

                if ((((size - ctvpt->pe) + ctvpt->next->ps) > min) && (((size - ctvpt->pe) + ctvpt->next->ps) < (max +2))) {

                    if ((ctvpt->cl > 0)&&(ctvpt->cl < 10)) {

                        if ((ctvpt->no > 0)&&(ctvpt->no < 10)) {
                            l = sprintf(line, "0%d;0%d;",ctvpt->cl,ctvpt->no);
                            strcat(file_content, line);
                            if (fprintf(f,"0%d;0%d;",ctvpt->cl,ctvpt->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                        else {
                            l = sprintf(line, "0%d;%d;",ctvpt->cl,ctvpt->no);
                            strcat(file_content, line);
                            if (fprintf(f,"0%d;%d;",ctvpt->cl,ctvpt->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                    }
                    else {

                        if ((ctvpt->no > 0)&&(ctvpt->no < 10)) {
                            l = sprintf(line, "%d;0%d;",ctvpt->cl,ctvpt->no);
                            strcat(file_content, line);
                            if (fprintf(f,"%d;0%d;",ctvpt->cl,ctvpt->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                        else {
                            l = sprintf(line, "%d;%d;",ctvpt->cl,ctvpt->no);
                            strcat(file_content, line);
                            if (fprintf(f,"%d;%d;",ctvpt->cl,ctvpt->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                    }

                    for(int i = 1; i <= (abs(ctvpt->pe - ctvpt->ps + 1)/3); i++) {
                        //PrtNLtToBuffer(file_content, ctvpt->next->nlt->head);
                        if (PrtNLtToFile(f,ctvpt->nlt->head, file_content) < 0) {
                            ret = -320;
                            break;
                        }
                    }

                    if (ret == -320) break;

                    if ((ctvpt->next->cl > 0)&&(ctvpt->next->cl < 10)) {

                        if ((ctvpt->next->no > 0)&&(ctvpt->next->no < 10)) {
                            l = sprintf(line, ";%d;%d;%d;0%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                            strcat(file_content, line);
                            if (fprintf(f,";%d;%d;%d;0%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                        else {
                            l = sprintf(line, ";%d;%d;%d;0%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                            strcat(file_content, line);
                            if (fprintf(f,";%d;%d;%d;0%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                    }
                    else {

                        if ((ctvpt->next->no > 0)&&(ctvpt->next->no < 10)) {
                            l = sprintf(line, ";%d;%d;%d;%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                            strcat(file_content, line);
                            if (fprintf(f,";%d;%d;%d;%d;0%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                        else {
                            l = sprintf(line, ";%d;%d;%d;%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no);
                            strcat(file_content, line);
                            if (fprintf(f,";%d;%d;%d;%d;%d;",abs(ctvpt->pe - ctvpt->ps + 1),ctvpt->ps,ctvpt->pe,ctvpt->next->cl,ctvpt->next->no) < 0) {
                                ret = -320;
                                break;
                            }
                        }
                    }

                    for(int i = 1; i <= (abs(ctvpt->next->pe - ctvpt->next->ps + 1)/3); i++) {
                        //PrtNLtToBuffer(file_content, ctvpt->next->nlt->head);
                        if (PrtNLtToFile(f,ctvpt->next->nlt->head, file_content) < 0) {
                            ret = -320;
                            break;
                        }
                    }

                    if (ret == -320) break;
                    l = sprintf(line, ";%d;%d;%d;>",abs(ctvpt->next->pe - ctvpt->next->ps + 1),ctvpt->next->ps,ctvpt->next->pe);
                    strcat(file_content, line);
                    if (fprintf(f,";%d;%d;%d;>",abs(ctvpt->next->pe - ctvpt->next->ps + 1),ctvpt->next->ps,ctvpt->next->pe) < 0) {
                        ret = -320;
                        break;
                    }

                    while (ctvpt->pe != ctnpt->no) {
                        ctnpt = ctnpt->next;
                    }

                    ctnpt = ctnpt->next;

                    int li = 0;

                    while (ctnpt->no != ctvpt->next->ps) {
                        l = sprintf(line, "%c",ctnpt->sgn);
                        strcat(file_content, line);
                        if (fprintf(f,"%c",ctnpt->sgn) < 0) {
                            ret = -320;
                            break;
                        }

                        li++;

                        ctnpt = ctnpt->next;
                    }

                    if (ret == -320) break;
                    l = sprintf(line, ";%d\n",li);
                    strcat(file_content, line);
                    if (fprintf(f,";%d\n",li) < 0) {
                        ret = -320;
                        break;
                    }
                }

                ctvpt = ctvpt->next;
            }
        }

        fclose(f);
    }
    else ret = -310;

    return ret;
}
/*
+---------------------------------------------------------------------------+
|  PrintError() – this function returns information on the basic errors     |
|  served.                                                                  |
+---------------------------------------------------------------------------+
*/
void PrintError(int e) {

    printf("\nError: ");

    if (e == -100) printf("%d The file sequence.fasta is missing, or there is an error with opening sequence.fasta.\n\n", e);
    if (e == -110) printf("%d The data (character) reading error from file sequence.fasta.\n\n", e);
    if (e == -120) printf("%d The data saving error to the linked list NLt.\n\n", e);
    if (e == -130) printf("%d The file sequence.fasta is nucleotides missing.\n\n", e);
    if (e == -140) printf("%d Initialization error of an additional linked list NLt.\n\n", e);
    if (e == -150) printf("%d The computer memory (RAM) is full or an error while writing a genome nucleotide into memory.\n\n", e);
    if (e == -160) printf("%d The file trs.txt is missing, or there is an error with opening trs.txt.\n\n", e);
    if (e == -170) printf("%d The file trs.txt is not formatted correctly. Check record in the trs.txt file.\n\n", e);
    if (e == -180) printf("%d The computer memory (RAM) is full or incorrect record in the trs.txt file.\n\n", e);
    if (e == -190) printf("%d Check the record of TRS motif in the in the trs.txt file \n\n", e);
    if (e == -200) printf("%d Incorrect read data (character) from the trs.txt file.\n\n", e);
    if (e == -210) printf("%d The computer memory (RAM) is full or incorrect record of the TRS motif position in the RAM.\n\n", e);
    if (e == -220) printf("%d The data saving error to the linked list NLt during searching for a TRS motif.\n\n", e);
    if (e == -230) printf("%d The genome taken from the sequence.fasta file contains less nucleotides than the TRS motif.\n\n", e);
    if (e == -240) printf("%d The computer memory (RAM) is full or an error during writing the flanking sequence of the linear case.\n\n", e);
    if (e == -250) printf("%d The computer memory (RAM) is full or an error during writing of the TRS motif position in the RAM of the circular case.\n\n", e);
    if (e == -260) printf("%d The data saving error to the linked list NLt or during searching for a TRS motif of the circular case.\n\n", e);
    if (e == -270) printf("%d The genome taken from the sequence.fasta file contains less nucleotides than the TRS motif of the circular case.\n\n", e);
    if (e == -280) printf("%d The computer memory (RAM) is full or an error during writing the flanking sequence of the circular case.\n\n", e);
    if (e == -290) printf("%d The file interiors.txt creating error of the linear case.\n\n", e);
    if (e == -300) printf("%d The file interiors.txt saving error of the linear case.\n\n", e);
    if (e == -310) printf("%d The file interiors.txt creating error of the circular case.\n\n", e);
    if (e == -320) printf("%d The file interiors.txt saving error of the circular case.\n\n", e);

}
/*
+---------------------------------------------------------------------------+
| ExitN() – this function free the memory assigned to the linked lists      |
| of NLt types after the occurrence of one of the basic errors served.      |                                                              |
+---------------------------------------------------------------------------+
*/
void ExitN(NLt *nlt, int e) {

    FreeNLt(nlt);
    PrintError(e);
    int t; scanf("%i",&t);
    exit(1);
}
/*
+---------------------------------------------------------------------------+
| ExitNN() – this function free the memory assigned to the linked lists     |
| of NLt types after the occurrence of one of the basic errors served.      |                                                              |
+---------------------------------------------------------------------------+
*/
void ExitNN(NLt *nlt1, NLt *nlt2, int e) {

    FreeNLt(nlt1);
    FreeNLt(nlt2);
    PrintError(e);
    int t; scanf("%i",&t);
    exit(1);
}
/*
+---------------------------------------------------------------------------+
| ExitNM() – this function free the memory assigned to the linked lists     |
| of MLt types after the occurrence of one of the basic errors served.      |                                                              |
+---------------------------------------------------------------------------+
*/
void ExitNM(NLt *nlt, MLt *mlt, int e) {

    FreeNLt(nlt);
    FreeMLt(mlt);
    PrintError(e);
    int t; scanf("%i",&t);
    exit(1);
}
/*
+---------------------------------------------------------------------------+
| ExitNMV() – this function free the memory assigned to the linked lists     |
| of VLt types after the occurrence of one of the basic errors served.      |                                                              |
+---------------------------------------------------------------------------+
*/
void ExitNMV(NLt *nlt, MLt *mlt, VLt *vlt, int e) {

    FreeNLt(nlt);
    FreeMLt(mlt);
    FreeVLt(vlt);
    PrintError(e);
    int t; scanf("%i",&t);
    exit(1);
}
char * PerformTRSCalculation(char *gfn, char* tfn, char* ifn, long long tmin, long long tmax, int mode){
    printf("\nname of genome file: %s", gfn);
    printf("\nname of input file: %s", tfn);
    printf("\nname of output file: %s", ifn);
    printf("\ntmin: %d", tmin);
    printf("\ntmax: %d", tmax);
    printf("\nmode: %d", mode);
    //char *gfn = "sequence.fasta", *tfn = "trs.txt", *ifn = "interiors.txt";
    long long int tsize = 0;
    //long long int tmin = 3;
    //long long int tmax = 6;
    printf("\n\nSTART\n");
    NLt gl; InitNLt(&gl);
    NLt gl2; InitNLt(&gl2);
    MLt ml; InitMLt(&ml);
    VLt vl; InitVLt(&vl);
    int  e = 0, opt = 0, len = 0;
    const int out_buffer_size = 5000 * 1024 * 1024;
    char *file_content = (char*)calloc(out_buffer_size, sizeof(char));
    if (mode==0){
        // linear case
        printf("\nLinear case...");
        tsize = ImportGenome(gfn,&gl);
        printf("\nsize of genome: %d", tsize);
        if (tsize < 0) ExitN(&gl,(int)tsize);
        len = ImportTRSToMLt(tfn,&ml);
        printf("\nsize of input: %d", len);
        if (len < 0) ExitNM(&gl,&ml,len);
        e = LC_TRSPositionsFindAndSaveToVLt(&ml,&gl,&vl,len);
        printf("\nstatus after LC_TRSPositionsFindAndSaveToVLt: %d", e);
        if (e < 0) ExitNMV(&gl,&ml,&vl,e);
        e = LC_InteriorsFindAndSaveToFile(ifn,&vl,&gl,tmin, tmax, file_content);
        printf("\nstatus after LC_InteriorsFindAndSaveToFile: %d", e);
        if (e < 0) ExitNMV(&gl,&ml,&vl,e);
    } else if (mode==1) {
        // circular case
        printf("\nCircular case...");
        tsize = ImportGenome(gfn,&gl);
        printf("\nsize of genome: %d", tsize);
        if (tsize < 0) ExitN(&gl,(int)tsize);
        e = CopyNLt(&gl2, &gl);
        if (e < 0) ExitNN(&gl,&gl2,e); JoinNLtWithNLt(&gl,&gl2);
        len = ImportTRSToMLt(tfn,&ml);
        printf("\nsize of input: %d", len);
        if (len < 0) ExitNM(&gl,&ml,len);
        e = CC_TRSPositionsFindAndSaveToVLt(&ml,&gl,&vl,len);
        printf("\nstatus after CC_TRSPositionsFindAndSaveToVLt: %d", e);
        if (e < 0) ExitNMV(&gl,&ml,&vl,e);
        e = CC_InteriorsFindAndSaveToFile(ifn,&vl,&gl,tsize,tmin,tmax, file_content);
        printf("\nstatus after CC_InteriorsFindAndSaveToFile: %d", e);
        if (e < 0) ExitNMV(&gl,&ml,&vl,e);
    } else {
        printf("mode %d not supported (0 - linear, 1 - circular are currently supported)", mode);
    }
    printf("\nEND");
    FreeNLt(&gl);
    FreeMLt(&ml);
    FreeVLt(&vl);
    return file_content;
}


int main()
{
    char *gfn = "sequence.fasta", *tfn = "trs.txt", *ifn = "interiors.txt";

    int  e = 0, opt = 0, len = 0;

    long long int tsize = 0;

    float tmin, tmax;

    NLt gl; InitNLt(&gl);
    NLt gl2; InitNLt(&gl2);
    MLt ml; InitMLt(&ml);
    VLt vl; InitVLt(&vl);
    const int out_buffer_size = 5000 * 1024 * 1024;
    char *file_content = (char*)calloc(out_buffer_size, sizeof(char));
    printf("\n");
    printf("1. Analysis of the linear case with conditions \n\n");
    printf("2. Analysis of the circular case with conditions \n\n");
    printf("Select option: ");

    scanf("%i",&opt);

        switch (opt)
        {
            case 0: break;


            case 1: printf("\n\n Set the minimum (Min) and the maximum (Max) lenght of interior:\n");
                    printf("\n  Min="); scanf("%f",&tmin);
                    printf("\n  Max="); scanf("%f",&tmax);

                    if (tmin < 1) {
                        printf("\n Error: Min < 1\n\n");
                        exit (1);
                    }

                    if (tmin > tmax) {
                        printf("\n Error: Min > Max\n\n");
                        exit (1);
                    }

                    printf("\n\nSTART\n");

                    if ((tsize = ImportGenome(gfn,&gl)) < 0) ExitN(&gl,(int)tsize);

                    if ((len = ImportTRSToMLt(tfn,&ml)) < 0) ExitNM(&gl,&ml,len);

                    if ((e = LC_TRSPositionsFindAndSaveToVLt(&ml,&gl,&vl,len)) < 0) ExitNMV(&gl,&ml,&vl,e);

                    if ((e = LC_InteriorsFindAndSaveToFile(ifn,&vl,&gl,tmin,tmax,file_content)) < 0) ExitNMV(&gl,&ml,&vl,e);

                    printf("END\n");

                    break;


            case 2: printf("\n\n Set the minimum (Min) and the maximum (Max) lenght of interior:\n");
                    printf("\n  Min="); scanf("%f",&tmin);
                    printf("\n  Max="); scanf("%f",&tmax);

                    if (tmin < 1) {
                        printf("\n Error: Min < 1\n\n");
                        exit (1);
                    }

                    if (tmin > tmax) {
                        printf("\n Error: Min > Max\n\n");
                        exit (1);
                    }

                    printf("\n\nSTART\n");

                    if ((tsize = ImportGenome(gfn,&gl)) < 0) ExitN(&gl,(int)tsize);

                    if ((e = CopyNLt(&gl2, &gl)) < 0) ExitNN(&gl,&gl2,e); JoinNLtWithNLt(&gl,&gl2);

                    if ((len = ImportTRSToMLt(tfn,&ml)) < 0) ExitNM(&gl,&ml,len);

                    if ((e = CC_TRSPositionsFindAndSaveToVLt(&ml,&gl,&vl,len)) < 0) ExitNMV(&gl,&ml,&vl,e);

                    if ((e = CC_InteriorsFindAndSaveToFile(ifn,&vl,&gl,tsize,tmin,tmax, file_content)) < 0) ExitNMV(&gl,&ml,&vl,e);

                    printf("END\n\n");

                    break;
        }

        FreeNLt(&gl);
        FreeMLt(&ml);
        FreeVLt(&vl);

        return 0;
}


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // char *()(char *, char *, char *, long, long, int)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 8), // char *
/*  2 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  4 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 9), // long
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 9),
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
};

static char * _cffi_d_PerformTRSCalculation(char * x0, char * x1, char * x2, long x3, long x4, int x5)
{
  return PerformTRSCalculation(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_PerformTRSCalculation(PyObject *self, PyObject *args)
{
  char * x0;
  char * x1;
  char * x2;
  long x3;
  long x4;
  int x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  char * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "PerformTRSCalculation", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (char *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x3 = _cffi_to_c_int(arg3, long);
  if (x3 == (long)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, long);
  if (x4 == (long)-1 && PyErr_Occurred())
    return NULL;

  x5 = _cffi_to_c_int(arg5, int);
  if (x5 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = PerformTRSCalculation(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(1));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_PerformTRSCalculation _cffi_d_PerformTRSCalculation
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "PerformTRSCalculation", (void *)_cffi_f_PerformTRSCalculation, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_PerformTRSCalculation },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  1,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  9,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__trs_omix(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__trs_omix(void) { return NULL; }
#  else
     init_trs_omix(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__trs_omix(void)
{
  return _cffi_init("_trs_omix", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_trs_omix(void)
{
  _cffi_init("_trs_omix", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
